// <auto-generated />
namespace Trippy_Land.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PNV014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PNV014));
        
        string IMigrationMetadata.Id
        {
            get { return "202010290111280_PNV014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
